# Generated by Django 4.0.6 on 2022-09-29 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'default_permissions': (), 'permissions': (('add_Post', 'Can add foo'), ('change_Post', 'Can change foo'), ('delete_Post', 'Can delete foo'), ('view_Post', 'Can view foo'), ('list_Post', 'Can list all foo'))},
        ),
    ]
