# Generated by Django 4.0.6 on 2022-08-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0003_myuser_date_of_birth_myuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
