# Generated by Django 4.0.6 on 2022-09-29 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0012_alter_myuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'default_permissions': (), 'permissions': (('add_MyUser', 'Can add foo'), ('change_MyUser', 'Can change foo'), ('delete_MyUser', 'Can delete foo'), ('view_MyUser', 'Can view foo'), ('list_MyUser', 'Can list all foo'))},
        ),
    ]
