# Generated by Django 4.0.6 on 2022-09-29 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0015_myuser_groups_myuser_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={},
        ),
    ]
